config/routes.rb
Rails.application.routes.draw do
  root 'engines#index'
  resources :engines, only: [:edit, :update, :index, :show]
  resources :connections, only: [:edit, :update]

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :engine, foreign_key: "engineName"

  def self.combine
    all.map { |connection| connection.sessionName }.join(",")
  end

  def get_exchange
    if exchange ==  1
      return "NYSE"
    elsif exchange ==  2
      return "NASDAQ"
    elsif exchange ==  3
      return "BATS"
    else
      return "DIRECT EDGE"
    end
  end

  def get_ip
    ip.to_s.insert(3, '.').insert(6, '.').insert(10, '.')
  end
end

app/models/engine.rb
class Engine < ActiveRecord::Base
  self.primary_key = :engineName
  has_many :usertoengines, foreign_key: "engineName"
  has_many :users,through: :usertoengines
  has_many :connections, foreign_key: "engineName"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :usertoengines
  has_many :engines, through: :usertoengines

  def self.combine
    all.map { |n| n.username }.join(",")
  end
end

app/models/usertoengine.rb
class Usertoengine < ActiveRecord::Base
  belongs_to :user
  belongs_to :engine, foreign_key: "engineName"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

  def edit
    @connection = Connection.find(params[:id])
    @engines = Engine.all
  end

  def update
    connection = Connection.find(params[:id])
    connection.update(connection_params)
    redirect_to engine_path(connection.engineName)
  end

  private

    def connection_params
      params.require(:connection).permit(:engineName, :exchange, :ip, :port)
    end
  end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController

  def index
    @engines = Engine.includes(:users, :connections)
  end

  def show
    engine = Engine.find(params[:id])
    @connections = engine.connections
  end

  def edit
    @engine = Engine.find(params[:id])
  end

  def update
    engine = Engine.find(params[:id])
    engine.update(engine_params)
    redirect_to engines_path
  end

private

  def engine_params
    params.require(:engine).permit(:lastRun)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/connections/edit.html.erb
<h1> Update Connection <%= @connection.idconnections %> </h1>


  <%= form_for @connection do |f| %>
      <%= f.label "Engine Name" %>
      <%= select("connection", "engineName", @engines.collect {|eng| [ eng.engineName, eng.engineName ] }, {include_blank: 'None'}) %><br>
      <%= f.label "Exchange"%>
      <%= f.text_field :exchange, placeholder: 'Phone Number' %><br>
      <%= f.label "IP"%>
      <%= f.text_field :ip, placeholder: 'Instagram Handle' %><br>
      <%= f.label "Port"%>
      <%= f.text_field :port, placeholder: 'Snapchat' %><br>
    <%= f.submit %>
  <% end %>

app/views/engines/edit.html.erb
<h1> Edit <%= @engine.engineName %> </h1>

<%= form_for @engine do |f| %>
  <%=f.date_select :lastRun  %>
  <%= f.time_select :lastRun , :ignore_date => true %>
 <%= f.submit %>
<% end %>

app/views/engines/index.html.erb
<table>
  <tr>
    <th>Engine Name</th>
    <th>Last Run</th>
    <th>Users</th>
    <th>Connections</th>
  </tr>

<% @engines.each do |engine| %>
  <tr>
    <th><a href= "<%= engine_path(engine.engineName) %>" > <%= engine.engineName %></a></th>
    <th><%= engine.lastRun %></th>
    <th><%= engine.users.combine %> <th>
    <th><%= engine.connections.combine %> <th>
    <th><%= link_to "Update Last Run", edit_engine_path(engine) %></th>
  </tr>
<% end %>
</table>

app/views/engines/show.html.erb
<table>
  <tr>
    <th>ID</th>
    <th>Engine Name</th>
    <th>Exchange</th>
    <th>IP</th>
    <th>Port</th>
  </tr>

<% @connections.each do |connection| %>
  <tr>
    <th><%= connection.idconnections %></th>
    <th><%= connection.engineName %></th>
    <th><%= connection.get_exchange %> <th>
    <th><%= connection.get_ip %> <th>
    <th><%= connection.port %> <th>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StrikeTechApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>